### ISSUE TITLE
SSE stands for Server-Sent Events

### ISSUE THREAD

**Issue by khalidabuhakmeh** [sisk-http/docs#1]
👋 Hi there, I was reading the docs and noticed you are referring to SSE as "Server-side Events". The correct term is Server-sent events (https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events).

Btw, this is a very cool project.

https://github.com/sisk-http/docs/blob/594fa427ceee5766a482edbf53ee3d5328bd94e2/static/view/docs/features/server-side-events.html#L9C1-L9C40

**Comment by CypherPotato** [comment]
Hello!

Thank you for your collaboration. Indeed, you must have been confused when writing that.

A correction will be there in the next commit, which also includes more content for the documentation.
